baseURL = "https://fatmatosunytu.github.io/"
relativeURLs = false
languageCode = "en"
title = "Bio_Code<-Cosmos"

timeZone = "UTC"
ignoreFiles = ["\\.DS_Store$"]

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  tagline = "Biyoinformatik ve Evren"
  description = "GitHub arÅŸivi ve repo incelemeleri"
  logo = "image (2).png"

[menu]
  [[menu.main]]
    name = "Home"
    url = ""
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 2

# Uncomment to enable multi-language structure.
# [languages]
#   [languages.en]
#     languageName = "English"
#     weight = 1
#   [languages.tr]
#     languageName = "Turkish"
#     weight = 2
